[package]
name = "vanitron"
version = "1.0.0"
edition = "2024"

[dependencies]
regex = "1.11"
bip39 = { version = "2.2", features = ["rand"] }
tiny-hderive = "0.3"
secp256k1 = "0.31"
sha3 = "0.10"
sha2 = "0.10"
bs58 = "0.5"
clap = { version = "4.5", features = ["derive"] }
num_cpus = "1.17"
anstream = "0.6"
anstyle = "1.0"
ctrlc = "3"
